FROM apache/spark:4.1.2-scala2.13-java21-python3-ubuntu

USER root

RUN python3 -m pip install pyspark "pyspark[sql]" pandas

RUN mkdir -p /opt/spark/work-dir/data/input && \
    mkdir -p /opt/spark/work-dir/data/output && \
    chmod 775 /opt/spark/work-dir/data/output && \
    chown -R spark:spark /opt/spark/work-dir/data/output

# RUN mkdir /opt/spark/conf && \
#     echo "spark.driver.extraClassPath       /opt/spark/jars/app-spark-common-4.0.0.jar" >> /opt/spark/conf/spark-defaults.conf && \
#     echo "spark.executor.extraClassPath     /opt/spark/jars/app-spark-common-4.0.0.jar" >> /opt/spark/conf/spark-defaults.conf && \
#     echo "spark.driver.extraJavaOptions     -Dsoftware.amazon.awssdk.sdk.execution.interceptors=com.yourcompany.s3.interceptor.GlobalS3V2Interceptor" >> /opt/spark/conf/spark-defaults.conf && \
#     echo "spark.executor.extraJavaOptions   -Dsoftware.amazon.awssdk.sdk.execution.interceptors=com.yourcompany.s3.interceptor.GlobalS3V2Interceptor" >> /opt/spark/conf/spark-defaults.conf

USER spark

# Community Jars
RUN wget \
    -P /opt/spark/jars/ \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.4.1/hadoop-common-3.4.1.jar
RUN wget \
    -P /opt/spark/jars/ \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.4.1/hadoop-aws-3.4.1.jar
RUN wget \
    -P /opt/spark/jars/ \
    https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/2.46.21/bundle-2.46.21.jar

# RUN wget \
#     -P /opt/spark/jars/ \
#     https://repo1.maven.org/maven2/com/databricks/spark-xml_2.12/0.18.0/spark-xml_2.12-0.18.0.jar
# RUN wget \
#     -P /opt/spark/jars/ \
#     https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.1/spark-sql-kafka-0-10_2.12-3.5.1.jar
# RUN wget \
#     -P /opt/spark/jars/ \
#     https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar
# RUN wget \
#     -P /opt/spark/jars/ \
#     https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.1/spark-token-provider-kafka-0-10_2.12-3.5.1.jar
# RUN wget \
#     -P /opt/spark/jars/ \
#     https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar
# RUN wget \
#     -P /opt/spark/jars/ \
#     https://repo1.maven.org/maven2/org/apache/spark/spark-hadoop-cloud_2.12/3.5.1/spark-hadoop-cloud_2.12-3.5.1.jar

# COPY ./resources/plugins/app-spark-common-4.0.0.jar /opt/spark/jars/
