# Set the root logger to TRACE level and attach it to the STDOUT appender
rootLogger.level = INFO
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT

# Configure the Console Appender targeting System.out
appender.console.type = Console
appender.console.name = STDOUT
appender.console.target = SYSTEM_OUT

# Define the log output format
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %p %c{1}: %m%n