services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: minio
    ports:
      - "9020:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      SPARK_DRIVER_OPTS: -verbose:class
      SPARK_EXECUTOR_OPTS: -verbose:class
    volumes:
      - ./resources/minio/config/entrypoint.sh:/entrypoint.sh:ro
      - ./resources/minio/config/docker-entrypoint-init.d:/docker-entrypoint-init.d:ro
    entrypoint: ["/entrypoint.sh"]
    profiles:
      - minio
      - backend
      - all
