reader:
  class_path: cdet_etl.readers.S3Reader
  properties:
    formats:
      - json
      - parquet
transformers:
  - cdet_etl.transformers.DatePartitionTransformer
  - cdet_etl.transformers.StatusTransformer
writer:
  class_path: cdet_etl.writers.S3Writer
  properties:
    bucket_name: output-2
    object_prefix: myfiles
    format: parquet
