services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: minio
    ports:
      - "9020:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      SPARK_DRIVER_OPTS: -verbose:class
      SPARK_EXECUTOR_OPTS: -verbose:class
    volumes:
      - ./services/minio/resources/config/entrypoint.sh:/entrypoint.sh:ro
      - ./services/minio/resources/config/docker-entrypoint-init.d:/docker-entrypoint-init.d:ro
    entrypoint: ["/entrypoint.sh"]
    profiles:
      - backend
      - all

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Configure KRaft role as both broker and controller
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      # Define listeners for inside the docker network and outside (localhost)
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"

      # Required cluster configuration
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    profiles:
      - backend
      - all

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9080:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
    profiles:
      - backend
      - all

  spark-master:
    build: ./services/spark
    container_name: spark-master
    ports:
      - "8080:8080" # Spark Master web UI
      - "7077:7077" # Spark Master port
      - "4040:4040" # Spark application UI
    environment:
      SPARK_MODE: master
      SPARK_PUBLIC_DNS: localhost
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./services/spark/resources/data:/opt/spark/work-dir/data
    profiles:
      - spark
      - all

  spark-worker-1:
    build: ./services/spark
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      SPARK_MODE: worker
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_CORES: 2
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ./services/spark/resources/data:/opt/spark/work-dir/data
    depends_on:
      - spark-master
    profiles:
      - spark
      - all

  spark-worker-2:
    build: ./services/spark
    container_name: spark-worker-2
    ports:
      - "8082:8082"
    environment:
      SPARK_MODE: worker
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_CORES: 2
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ./services/spark/resources/data:/opt/spark/work-dir/data
    depends_on:
      - spark-master
    profiles:
      - spark
      - all

  spark-worker-3:
    build: ./services/spark
    container_name: spark-worker-3
    ports:
      - "8083:8083"
    environment:
      SPARK_MODE: worker
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_WEBUI_PORT: 8083
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_CORES: 2
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ./services/spark/resources/data:/opt/spark/work-dir/data
      - ./services/spark/resources/config/log4j2.properties:/opt/spark/conf/log4j2.properties
    depends_on:
      - spark-master
    profiles:
      - spark
      - all

  spark-submit-client:
    build: ./services/spark
    container_name: spark-submit-client
    environment:
      SPARK_MODE: client
      PYTHONPATH: /opt/spark-jobs
    working_dir: /opt/spark-jobs
    command: tail -f /dev/null
    volumes:
      - ./services/spark/resources/data:/opt/spark/work-dir/data
      - ./services/spark/jobs:/opt/spark-jobs
    depends_on:
      - spark-master
    profiles:
      - spark
      - all
