worker_processes auto;
events {
    worker_connections 1024;
}
http {
    server {
        # resolver 10.89.0.1; # podman resolver
        resolver 127.0.0.11; # docker resolver
        listen 443 ssl;
        server_name devpi.local.lab;
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        ssl_client_certificate /etc/nginx/certs/ca.crt;
        # ssl_verify_client on;

        location / {
            set $backend http://localhost:3141;
            proxy_pass $backend;
            proxy_set_header X-outside-url $scheme://$host;
            proxy_set_header Host $host;            
            proxy_set_header X-Real-IP $remote_addr;
            # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # proxy_set_header X-Client-Cert $ssl_client_cert;
            # proxy_set_header X-Client-Cert-DN $ssl_client_s_dn;
        }
    }
}