worker_processes auto;

events {
    worker_connections 1024;
}

http {
    client_max_body_size 500M;
    proxy_read_timeout 60s;
    
    server {
        # resolver 10.89.0.1; # podman resolver
        resolver 127.0.0.11; # docker resolver
        listen 443 ssl;
        server_name devpi.local.lab;
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        ssl_client_certificate /etc/nginx/certs/ca.crt;

        location / {
            set $backend http://devpi-server:3141;
            proxy_pass $backend;
            proxy_set_header X-outside-url $scheme://$host:$server_port;
            proxy_set_header Host $host;            
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}