reader:
  class_path: cdet_etl.readers.S3Reader
  properties:
    client_name: minio
    formats:
      - json
      - parquet
transformers:
  - class_path: cdet_etl.transformers.DatePartitionTransformer
    properties:
      timestamp_field: event_time
  - class_path: cdet_etl.transformers.StatusTransformer
writer:
  class_path: cdet_etl.writers.S3Writer
  properties:
    client_name: minio
    bucket_name: output-1
    object_prefix: myfiles
    format: json
